name: WildUI
main: WildUi\Main
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0, 3.1.0, 3.2.0, 3.3.0]
version: 0.0.1
author: BajanVlogs

commands:
 wildui:
  description: "Wild a player using CustomUI"
